@backend_api_HostAddress = http://localhost:5005

GET {{backend_api_HostAddress}}/health
Accept: application/json

###

GET {{backend_api_HostAddress}}/api/cards
Accept: application/json

###

GET {{backend_api_HostAddress}}/api/transactions
Accept: application/json

