// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_api.Data;

#nullable disable

namespace backend_api.Migrations
{
    [DbContext(typeof(TreasuryDbContext))]
    partial class TreasuryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_api.Domain.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Expires")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullNumber")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<string>("Holder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<decimal>("Limit")
                        .HasColumnType("numeric");

                    b.Property<string>("RelativeBg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Spent")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e43dbfb4-e5de-4d76-b51c-43db35948951"),
                            CardType = "Platinum",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Expires = "12/26",
                            FullNumber = "4412 8821 0092 4556",
                            Holder = "Sarah Jenkins",
                            Last4 = "4412",
                            Limit = 25000m,
                            RelativeBg = "#0F172A",
                            Spent = 16250.40m,
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("b25c345a-c603-4fba-80d5-1c3905c317f2"),
                            CardType = "Physical",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Expires = "08/25",
                            FullNumber = "4912 3781 8901 0212",
                            Holder = "David Chen",
                            Last4 = "8901",
                            Limit = 10000m,
                            RelativeBg = "#1E293B",
                            Spent = 1250.00m,
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("76db01aa-2782-411a-8bb7-09a8ab7d91cb"),
                            CardType = "Platinum",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Expires = "11/27",
                            FullNumber = "4112 0044 1122 8989",
                            Holder = "Mark Thompson",
                            Last4 = "1122",
                            Limit = 50000m,
                            RelativeBg = "#475569",
                            Spent = 0.00m,
                            Status = "LOCKED"
                        },
                        new
                        {
                            Id = new Guid("9420db20-8041-4ea6-ab7b-d68a2db7a31b"),
                            CardType = "Virtual",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Expires = "05/26",
                            FullNumber = "4412 9901 5564 3321",
                            Holder = "Elena Rodriguez",
                            Last4 = "5564",
                            Limit = 5000m,
                            RelativeBg = "#334155",
                            Spent = 1450.45m,
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("backend_api.Domain.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CardLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = "#TRX-99210",
                            Amount = -1240.00m,
                            CardLast4 = "4412",
                            Category = "Infrastructure",
                            Date = new DateTime(2023, 10, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "AWS Cloud Services",
                            Entity = "Proton North America",
                            OriginalCurrency = "USD",
                            Status = "Cleared"
                        },
                        new
                        {
                            Id = "#TRX-99208",
                            Amount = -12400.00m,
                            CardLast4 = "8901",
                            Category = "Travel",
                            Date = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "United Airlines - Q4",
                            Entity = "Global Executive",
                            OriginalCurrency = "USD",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = "#TRX-98144",
                            Amount = 2400000.00m,
                            CardLast4 = "4412",
                            Category = "Infrastructure",
                            Date = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Goldman Sachs Treasury Transfer",
                            Entity = "Master Holding",
                            OriginalCurrency = "USD",
                            Status = "Cleared"
                        },
                        new
                        {
                            Id = "#TRX-99150",
                            Amount = -156000.00m,
                            CardLast4 = "5564",
                            Category = "Software & SaaS",
                            Date = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Marsh McLennan Software",
                            Entity = "Proton UK Ltd",
                            OriginalCurrency = "USD",
                            Status = "Flagged"
                        },
                        new
                        {
                            Id = "#TRX-00101",
                            Amount = -12.45m,
                            CardLast4 = "4412",
                            Category = "Entertainment",
                            Date = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Starbucks Coffee - Strategy",
                            Entity = "Director Lunch",
                            OriginalCurrency = "USD",
                            Status = "Cleared"
                        },
                        new
                        {
                            Id = "#TRX-00102",
                            Amount = -49.00m,
                            CardLast4 = "4412",
                            Category = "Software",
                            Date = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GitHub Inc. - Enterprise Seats",
                            Entity = "Development Tooling",
                            OriginalCurrency = "USD",
                            Status = "Pending"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
